"""AZ master skeleton: SK_AZ_Master = exact copy of the MetaHuman body skeleton + our extra leaf bones.

Why: /Game/MetaHumans/Common/** and the hero body are regenerated by MetaHuman assembly (and not in git), so the
master lives in our folder. The hero keeps metahuman_base_skel and plays master animations through
CompatibleSkeletons (metahuman_fixup.py). Bones of the MetaHuman part are never renamed, moved or re-oriented.

Run in the editor (Python):   MODE = "duplicate" | "finish" | "verify";  exec(open(r"C:/UnrealEngine/Games/AZ/Tools/az_master_skeleton.py").read())
Between "duplicate" and "finish" the mesh copy is moved onto SK_AZ_Master in C++ (USkeletalMesh::SetSkeleton is not
reachable from Python).
MODE "add_bones" on the MASTER mesh: the master skeleton is referenced by that one mesh only, so UE's commit rebuilds the
skeleton FROM the mesh - its ref pose becomes the hero's proportions and its per-bone translation retargeting modes get
scrambled. Afterwards, in C++ (no Python API): copy metahuman_base_skel's raw ref pose (FReferenceSkeletonModifier) and
its GetBoneTranslationRetargetingMode per bone onto SK_AZ_Master, save, then MODE "verify" and MODE "compat_test"
(retarget=False AND retarget=True must both PASS). On the hero body (skeleton shared by many assets) UE merges instead,
nothing to fix there.
Report: Saved/az_master_report.txt
"""
import math
import os
import unreal

MODE = globals().get("MODE", "verify")

SRC_SKELETON = "/Game/MetaHumans/Common/Female/Medium/NormalWeight/Body/metahuman_base_skel"
SRC_MESH = "/Game/AZ/Blueprints/Character/AZ_MHC_Hero/Body/SKM_MHC_Hero_BodyMesh"
MASTER_SKELETON = "/Game/AZ/Blueprints/Character/Master/SK_AZ_Master"      # in git
MASTER_MESH = "/Game/AZ/Assets/Characters/Master/SKM_AZ_Master"             # preview/retarget mesh, rebuilt by this script
REPORT = os.path.join(unreal.Paths.project_saved_dir(), "az_master_report.txt")

# Our extra bones: (name, parent). NEW LEAVES ONLY, local rest transform = identity (the bone sits exactly on its hand),
# so animations without these tracks carry them rigidly with the hand - weapons/props behave like today's hand sockets.
# Prefix az_ so no pack track can hit them by name (SurvivalMan anims, played on the hero, carry their own weapon_r).
EXTRA_BONES = [
    ("az_weapon_r", "hand_r"),   # gun; RifleMega reloads write the gun path relative to the hand here
    ("az_prop_r", "hand_r"),     # throwables / props held in the right hand
    ("az_prop_l", "hand_l"),     # props held in the left hand
]
TARGET_MESH = globals().get("TARGET_MESH", MASTER_MESH)   # add_bones target: the master mesh, or the hero body (fixup)

EAL = unreal.EditorAssetLibrary
lines = []


def log(msg):
    lines.append(msg)
    unreal.log("AZMASTER " + msg)


def file_of(asset_path):
    return unreal.Paths.convert_relative_path_to_full(
        unreal.Paths.project_content_dir() + asset_path[len("/Game/"):] + ".uasset")


def mesh_bones(mesh):
    mod = unreal.SkeletonModifier()
    mod.set_skeletal_mesh(mesh)
    names = [str(n) for n in mod.get_all_bone_names()]
    return {n: (str(mod.get_parent_name(n)), mod.get_bone_transform(n, False)) for n in names}, names


def skeleton_bones(skeleton):
    pose = unreal.AnimPoseExtensions.get_reference_pose(skeleton)
    names = [str(n) for n in unreal.AnimPoseExtensions.get_bone_names(pose)]
    return {n: unreal.AnimPoseExtensions.get_ref_bone_pose(pose, n, unreal.AnimPoseSpaces.LOCAL) for n in names}, names


def tdiff(a, b):
    dl = (a.translation - b.translation).length()
    qa, qb = a.rotation, b.rotation
    if (qa.x, qa.y, qa.z, qa.w) == (qb.x, qb.y, qb.z, qb.w):
        dq = 0.0   # identical bits (acos of a not-exactly-unit dot would report ~4e-8 rad of pure noise)
    else:
        dot = min(1.0, abs(qa.x * qb.x + qa.y * qb.y + qa.z * qb.z + qa.w * qb.w))
        dq = 2.0 * math.acos(dot)
    ds = (a.scale3d - b.scale3d).length()
    return dl, dq, ds


def compare(tag, a, a_names, b, b_names, pairs):
    missing = [n for n in a_names if n not in b]
    order_same = a_names == b_names[:len(a_names)]
    worst = (0.0, 0.0, 0.0, "")
    parent_bad = []
    for n in a_names:
        if n not in b:
            continue
        ta = a[n][1] if pairs else a[n]
        tb = b[n][1] if pairs else b[n]
        if pairs and a[n][0] != b[n][0]:
            parent_bad.append(n)
        dl, dq, ds = tdiff(ta, tb)
        if dl + dq + ds > worst[0] + worst[1] + worst[2]:
            worst = (dl, dq, ds, n)
    ok = not missing and not parent_bad and order_same and worst[0] < 1e-4 and worst[1] < 1e-6 and worst[2] < 1e-6
    log("%s: %s | bones %d vs %d, missing %d, parent mismatch %d, same order %s, worst dLoc %.2e cm dRot %.2e rad dScale %.2e (%s)"
        % (tag, "PASS" if ok else "FAIL", len(a_names), len(b_names), len(missing), len(parent_bad), order_same,
           worst[0], worst[1], worst[2], worst[3]))
    if missing:
        log("   missing: %s" % missing[:20])
    if parent_bad:
        log("   parent mismatch: %s" % parent_bad[:20])
    return ok


def duplicate():
    """Step 1 of 3. Python cannot assign USkeletalMesh::Skeleton (read-only), so the build is:
    MODE=duplicate (here, nothing saved) -> SetSkeleton(SK_AZ_Master) in C++ -> MODE=finish (saves + verifies)."""
    if EAL.does_asset_exist(MASTER_SKELETON) or EAL.does_asset_exist(MASTER_MESH):
        log("duplicate: master already exists - nothing done (delete it by hand to rebuild)")
        return
    for d in (MASTER_SKELETON.rsplit("/", 1)[0], MASTER_MESH.rsplit("/", 1)[0]):
        EAL.make_directory(d)
    sk = EAL.duplicate_asset(SRC_SKELETON, MASTER_SKELETON)
    mesh = EAL.duplicate_asset(SRC_MESH, MASTER_MESH)
    log("duplicate: skeleton %s, mesh %s" % (bool(sk), bool(mesh)))
    mesh.set_editor_property("post_process_anim_blueprint", None)   # MetaHuman correctives are built for metahuman_base_skel
    mesh.set_editor_property("physics_asset", None)
    sk.set_editor_property("compatible_skeletons", [])              # the master is a source, it consumes nothing
    log("duplicate: done, NOT saved - next: assign the skeleton in C++, then MODE=finish")


def finish():
    sk = unreal.load_asset(MASTER_SKELETON)
    mesh = unreal.load_asset(MASTER_MESH)
    if not (sk and mesh):
        log("finish: master missing")
        return False
    got = mesh.get_editor_property("skeleton").get_path_name()
    if got != sk.get_path_name():
        log("finish: STOP - mesh still on %s, nothing saved" % got)
        return False
    for p in (MASTER_SKELETON, MASTER_MESH):
        before = os.path.getmtime(file_of(p)) if os.path.exists(file_of(p)) else 0
        EAL.save_asset(p, only_if_is_dirty=False)
        after = os.path.getmtime(file_of(p)) if os.path.exists(file_of(p)) else 0
        log("finish: saved %s (file written %s)" % (p, after > before))
    return True


def mesh_stats(mesh):
    ses = unreal.get_editor_subsystem(unreal.SkeletalMeshEditorSubsystem)
    s = {}
    try:
        lods = ses.get_lod_count(mesh)
        s["verts"] = [ses.get_num_verts(mesh, i) for i in range(lods)]
    except Exception as e:
        s["verts"] = "ERR %s" % str(e)[:60]
    try:
        s["morphs"] = len(mesh.get_all_morph_target_names())
    except Exception as e:
        s["morphs"] = "ERR %s" % str(e)[:60]
    try:
        s["sockets"] = sorted(str(mesh.get_socket_by_index(i).get_editor_property("socket_name")) for i in range(mesh.num_sockets()))
    except Exception as e:
        s["sockets"] = "ERR %s" % str(e)[:60]
    s["bones"] = len(mesh_bones(mesh)[1])
    return s


def add_bones(mesh_path):
    """Idempotent: adds the EXTRA_BONES the mesh lacks (merged into its skeleton by the commit), saves mesh + skeleton."""
    mesh = unreal.load_asset(mesh_path)
    have, _ = mesh_bones(mesh)
    todo = [(n, p) for n, p in EXTRA_BONES if n not in have]
    before = mesh_stats(mesh)
    log("add_bones %s: before %s" % (mesh_path, before))
    if not todo:
        log("add_bones: all extra bones already present - nothing to do")
        return
    mod = unreal.SkeletonModifier()
    mod.set_skeletal_mesh(mesh)
    ok = mod.add_bones([n for n, _ in todo], [p for _, p in todo], [unreal.Transform() for _ in todo])
    committed = mod.commit_skeleton_to_skeletal_mesh() if ok else False
    log("add_bones: add %s, commit %s (%s)" % (ok, committed, [n for n, _ in todo]))
    if not committed:
        log("add_bones: STOP - nothing saved")
        return
    after = mesh_stats(mesh)
    log("add_bones: after  %s" % after)
    same = before["verts"] == after["verts"] and before["morphs"] == after["morphs"] and before["sockets"] == after["sockets"]
    log("add_bones: verts/morphs/sockets unchanged: %s" % same)
    sk_path = mesh.get_editor_property("skeleton").get_path_name().split(".")[0]
    for p in (mesh_path, sk_path):
        t0 = os.path.getmtime(file_of(p)) if os.path.exists(file_of(p)) else 0
        EAL.save_asset(p, only_if_is_dirty=False)
        t1 = os.path.getmtime(file_of(p)) if os.path.exists(file_of(p)) else 0
        log("add_bones: saved %s (file written %s)" % (p, t1 > t0))


def check_extras(tag, bones_by_name):
    bad = []
    for n, p in EXTRA_BONES:
        if n not in bones_by_name:
            bad.append("%s missing" % n)
            continue
        par, t = bones_by_name[n]
        dl, dq, ds = tdiff(t, unreal.Transform())
        if par != p or dl > 1e-6 or dq > 1e-6 or ds > 1e-6:
            bad.append("%s parent=%s dLoc=%.2e dRot=%.2e" % (n, par, dl, dq))
    log("%s extra bones: %s" % (tag, "PASS" if not bad else "FAIL %s" % bad))
    return not bad


TEST_CLIP = globals().get("TEST_CLIP", "/Game/AZ/Assets/RifleMega/Rifle_ReloadingSet/Winchester/AZ_RTG_MH_Rifle01_St_Reload_Winch")
TEST_DIR = "/Game/AZ/Temp/MasterCompatTest"


def eval_opts(mesh, retarget):
    o = unreal.AnimPoseEvaluationOptions()
    o.set_editor_property("optional_skeletal_mesh", mesh)
    o.set_editor_property("evaluation_type", unreal.AnimDataEvalType.RAW)
    o.set_editor_property("should_retarget", retarget)
    o.set_editor_property("extract_root_motion", False)
    return o


MASTER_TEST_CLIP = globals().get("MASTER_TEST_CLIP", "/Game/AZ/Assets/Master/RifleMega/Rifle_ReloadingSet/Winchester/AZ_MST_Rifle01_St_Reload_Winch")


def compat_compare():
    """Proof that a master clip plays on the hero exactly like its MetaHuman original: evaluate both on the HERO BODY
    (the master clip goes through the CompatibleSkeletons remapping), with translation retargeting off and on, and
    compare every MetaHuman bone (az_* bones are master-only tracks). Creates and deletes nothing."""
    APE = unreal.AnimPoseExtensions
    src = unreal.load_asset(TEST_CLIP)
    dst = unreal.load_asset(MASTER_TEST_CLIP)
    hero = unreal.load_asset(SRC_MESH)
    n_keys = min(unreal.AnimationLibrary.get_num_keys(src), unreal.AnimationLibrary.get_num_keys(dst))
    bones = [b for b in mesh_bones(hero)[1] if not b.startswith("az_")]
    log("compat_compare: %s vs %s (%s), %d keys, %d bones" % (src.get_name(), dst.get_name(),
                                                           dst.get_editor_property("skeleton").get_name(), n_keys, len(bones)))
    for retarget in (False, True):
        o = eval_opts(hero, retarget)
        worst_l = [0.0, 0.0, ""]
        worst_w = [0.0, 0.0, ""]
        for k in range(0, n_keys, 2):
            pa = APE.get_anim_pose_at_frame(src, k, o)
            pb = APE.get_anim_pose_at_frame(dst, k, o)
            for b in bones:
                for space, worst in ((unreal.AnimPoseSpaces.LOCAL, worst_l), (unreal.AnimPoseSpaces.WORLD, worst_w)):
                    dl, dq, _ = tdiff(APE.get_bone_pose(pa, b, space), APE.get_bone_pose(pb, b, space))
                    if dl + dq > worst[0] + worst[1]:
                        worst[:] = [dl, dq, "%s@%d" % (b, k)]
        ok = worst_w[0] < 1e-3 and worst_w[1] < 1e-5
        log("compat_compare %s retarget=%s: local worst dLoc %.2e cm dRot %.2e rad (%s) | world worst dLoc %.2e cm dRot %.2e rad (%s)"
            % ("PASS" if ok else "FAIL", retarget, worst_l[0], worst_l[1], worst_l[2], worst_w[0], worst_w[1], worst_w[2]))


def compat_test():
    """(Superseded by compat_compare - this one creates AND deletes a temp asset in one call, which froze the editor.)"""
    APE = unreal.AnimPoseExtensions
    src = unreal.load_asset(TEST_CLIP)
    hero = unreal.load_asset(SRC_MESH)
    master_sk = unreal.load_asset(MASTER_SKELETON)
    n_keys = unreal.AnimationLibrary.get_num_keys(src)
    n_frames = unreal.AnimationLibrary.get_num_frames(src)
    length = src.get_play_length()
    fps = int(round(n_frames / length)) if length > 0 else 30
    tracks = [str(t) for t in unreal.AnimationLibrary.get_animation_track_names(src)]
    log("compat_test: %s keys %d frames %d fps %d tracks %d" % (src.get_name(), n_keys, n_frames, fps, len(tracks)))

    # raw keys of the source, on its own skeleton
    own = unreal.AnimPoseEvaluationOptions()
    own.set_editor_property("evaluation_type", unreal.AnimDataEvalType.RAW)
    own.set_editor_property("should_retarget", False)
    own.set_editor_property("extract_root_motion", False)
    keys = {b: ([], [], []) for b in tracks}
    for k in range(n_keys):
        pose = APE.get_anim_pose_at_frame(src, k, own)
        for b in tracks:
            t = APE.get_bone_pose(pose, b, unreal.AnimPoseSpaces.LOCAL)
            keys[b][0].append(t.translation)
            keys[b][1].append(t.rotation)
            keys[b][2].append(t.scale3d)

    if EAL.does_directory_exist(TEST_DIR):
        EAL.delete_directory(TEST_DIR)
    factory = unreal.AnimSequenceFactory()
    factory.set_editor_property("target_skeleton", master_sk)
    dst = unreal.AssetToolsHelpers.get_asset_tools().create_asset(src.get_name() + "_OnMaster", TEST_DIR, unreal.AnimSequence, factory)
    c = dst.controller
    c.open_bracket("AZ master compat test copy", False)
    try:
        c.set_frame_rate(unreal.FrameRate(fps, 1), False)
        c.set_number_of_frames(unreal.FrameNumber(n_frames), False)
        for b in tracks:
            c.add_bone_curve(unreal.Name(b), False)
            if not c.set_bone_track_keys(unreal.Name(b), keys[b][0], keys[b][1], keys[b][2], False):
                raise RuntimeError("set_bone_track_keys failed on %s" % b)
    finally:
        c.close_bracket(False)
    log("compat_test: master copy %s on %s, keys %d" % (dst.get_name(), dst.get_editor_property("skeleton").get_name(),
                                                        unreal.AnimationLibrary.get_num_keys(dst)))

    hero_bones = mesh_bones(hero)[1]
    for retarget in (False, True):
        o = eval_opts(hero, retarget)
        worst_l = [0.0, 0.0, ""]
        worst_w = [0.0, 0.0, ""]
        for k in range(0, n_keys, 2):
            pa = APE.get_anim_pose_at_frame(src, k, o)
            pb = APE.get_anim_pose_at_frame(dst, k, o)
            for b in hero_bones:
                for space, worst in ((unreal.AnimPoseSpaces.LOCAL, worst_l), (unreal.AnimPoseSpaces.WORLD, worst_w)):
                    dl, dq, _ = tdiff(APE.get_bone_pose(pa, b, space), APE.get_bone_pose(pb, b, space))
                    if dl + dq > worst[0] + worst[1]:
                        worst[:] = [dl, dq, "%s@%d" % (b, k)]
        ok = worst_w[0] < 1e-3 and worst_w[1] < 1e-5
        log("compat_test %s retarget=%s: local worst dLoc %.2e cm dRot %.2e rad (%s) | world worst dLoc %.2e cm dRot %.2e rad (%s)"
            % ("PASS" if ok else "FAIL", retarget, worst_l[0], worst_l[1], worst_l[2], worst_w[0], worst_w[1], worst_w[2]))

    EAL.delete_directory(TEST_DIR)
    log("compat_test: temp folder removed %s" % (not EAL.does_directory_exist(TEST_DIR)))


def verify():
    sk = unreal.load_asset(MASTER_SKELETON)
    mesh = unreal.load_asset(MASTER_MESH)
    src_sk = unreal.load_asset(SRC_SKELETON)
    src_mesh = unreal.load_asset(SRC_MESH)
    if not (sk and mesh):
        log("verify: master missing (skeleton %s, mesh %s)" % (bool(sk), bool(mesh)))
        return
    log("verify: mesh.skeleton = %s" % mesh.get_editor_property("skeleton").get_path_name())
    log("verify: mesh post-process = %s" % mesh.get_editor_property("post_process_anim_blueprint"))
    a, an = skeleton_bones(src_sk)
    b, bn = skeleton_bones(sk)
    ok1 = compare("skeleton  metahuman_base_skel -> SK_AZ_Master", a, an, b, bn, False)
    a, an = mesh_bones(src_mesh)
    b, bn = mesh_bones(mesh)
    ok2 = compare("mesh      hero body -> SKM_AZ_Master       ", a, an, b, bn, True)
    extra = [n for n in bn if n not in a]
    log("verify: master-only bones: %s" % (extra if extra else "none"))
    ok3 = check_extras("master mesh", b) if extra else True
    log("VERIFY %s" % ("ALL PASS" if ok1 and ok2 and ok3 else "FAIL"))


lines.append("MODE %s" % MODE)
if MODE == "duplicate":
    duplicate()
elif MODE == "finish":
    if finish():
        verify()
elif MODE == "add_bones":
    add_bones(TARGET_MESH)
    verify()
elif MODE == "compat_compare":
    compat_compare()
else:
    verify()
with open(REPORT, "w", encoding="utf-8") as f:
    f.write("\n".join(lines) + "\n")
import gc
gc.collect()
